/**
  * @file lis2dh12_dev.c
  * @author generated by mrt-device.py
  * @brief register defintions for LIS2DH12 device
  * 
  */

#include "lis2dh12_dev.h"



/**
 * @brief initializes registers for device
 * @param dev ptr to LIS2DH12 device
 */
void LIS2DH12_init_regs(LIS2DH12_t* dev)
{
    REG_INIT( dev->mStatusAux , 0x07, uint8_t, REG_PERM_R  );
    REG_INIT( dev->mOutTemp , 0x0c, uint16_t, REG_PERM_R  );
    REG_INIT( dev->mWhoAmI , 0x0f, uint8_t, REG_PERM_R  );
    REG_INIT( dev->mCtrl0 , 0x1e, uint8_t, REG_PERM_RW  );
    REG_INIT( dev->mTempCfg , 0x1f, uint8_t, REG_PERM_RW  );
    REG_INIT( dev->mCtrl1 , 0x20, uint8_t, REG_PERM_RW  );
    REG_INIT( dev->mCtrl2 , 0x21, uint8_t, REG_PERM_RW  );
    REG_INIT( dev->mCtrl3 , 0x22, uint8_t, REG_PERM_RW  );
    REG_INIT( dev->mCtrl4 , 0x23, uint8_t, REG_PERM_RW  );
    REG_INIT( dev->mCtrl5 , 0x24, uint8_t, REG_PERM_RW  );
    REG_INIT( dev->mCtrl6 , 0x25, uint8_t, REG_PERM_RW  );
    REG_INIT( dev->mReference , 0x26, uint8_t, REG_PERM_RW  );
    REG_INIT( dev->mStatus , 0x27, uint8_t, REG_PERM_R  );
    REG_INIT( dev->mOutX , 0x28, uint16_t, REG_PERM_R  );
    REG_INIT( dev->mOutY , 0x2a, uint16_t, REG_PERM_R  );
    REG_INIT( dev->mOutZ , 0x2c, uint16_t, REG_PERM_R  );
    REG_INIT( dev->mFifoCtrl , 0x2e, uint8_t, REG_PERM_RW  );
    REG_INIT( dev->mFifoSrc , 0x2f, uint8_t, REG_PERM_R  );
    REG_INIT( dev->mInt1Cfg , 0x30, uint8_t, REG_PERM_RW  );
    REG_INIT( dev->mInt1Src , 0x31, uint8_t, REG_PERM_R  );
    REG_INIT( dev->mInt1Ths , 0x32, uint8_t, REG_PERM_RW  );
    REG_INIT( dev->mInt1Duration , 0x33, uint8_t, REG_PERM_RW  );
    REG_INIT( dev->mInt2Cfg , 0x34, uint8_t, REG_PERM_RW  );
    REG_INIT( dev->mInt2Src , 0x35, uint8_t, REG_PERM_R  );
    REG_INIT( dev->mInt2Ths , 0x36, uint8_t, REG_PERM_RW  );
    REG_INIT( dev->mInt2Duration , 0x37, uint8_t, REG_PERM_RW  );
    REG_INIT( dev->mClickCfg , 0x38, uint8_t, REG_PERM_RW  );
    REG_INIT( dev->mClickSrc , 0x39, uint8_t, REG_PERM_R  );
    REG_INIT( dev->mClickThs , 0x3a, uint8_t, REG_PERM_RW  );
    REG_INIT( dev->mTimeLimit , 0x3b, uint8_t, REG_PERM_RW  );
    REG_INIT( dev->mTimeLatency , 0x3c, uint8_t, REG_PERM_RW  );
    REG_INIT( dev->mTimeWindow , 0x3d, uint8_t, REG_PERM_RW  );
    REG_INIT( dev->mActThs , 0x3e, uint8_t, REG_PERM_RW  );
    REG_INIT( dev->mActDur , 0x3f, uint8_t, REG_PERM_RW  );
}



mrt_status_t LIS2DH12_init_i2c(LIS2DH12_t* dev, mrt_i2c_handle_t i2c)
{
    mrt_status_t status;

    LIS2DH12_init_regs(dev);

    status = init_i2c_register_device(dev->mRegDev, i2c, LIS_I2C_ADDRESS, 1 );
    
    /*user-block-init-i2c*/
    /*user-block-init-i2c*/
    
    return MRT_STATUS_OK;
}
mrt_status_t lis_init_spi(LIS2DH12_t* dev, mrt_spi_handle_t spi)
{
    LIS2DH12_init_regs(dev)

    /*user-block-spi*/
    /*user-block-spi*/

    return MRT_STATUS_OK;
}
