/**
  * @file lis2dh12_dev.h
  * @author generated by mrt-device tool
  * @brief values and constants for the LIS2DH12 device
  * 
  */

#define LIS2DH12_I2C_ADDRESS 0x52
#define LIS2DH12_REG_ADDR_SIZE 1


/*******************************************************************************
  Register Addresses                                                                              
*******************************************************************************/

#define LIS_REG_STATUS_AUX_ADDR                       0x07
#define LIS_REG_OUT_TEMP_ADDR                       0x0C
#define LIS_REG_WHO_AM_I_ADDR                       0x0F
#define LIS_REG_CTRL0_ADDR                       0x1E
#define LIS_REG_TEMP_CFG_ADDR                       0x1F
#define LIS_REG_CTRL1_ADDR                       0x20
#define LIS_REG_CTRL2_ADDR                       0x21
#define LIS_REG_CTRL3_ADDR                       0x22
#define LIS_REG_CTRL4_ADDR                       0x23
#define LIS_REG_CTRL5_ADDR                       0x24
#define LIS_REG_CTRL6_ADDR                       0x25
#define LIS_REG_REFERENCE_ADDR                       0x26
#define LIS_REG_STATUS_ADDR                       0x27
#define LIS_REG_OUT_X_ADDR                       0x28
#define LIS_REG_OUT_Y_ADDR                       0x2A
#define LIS_REG_OUT_Z_ADDR                       0x2C
#define LIS_REG_FIFO_CTRL_ADDR                       0x2E
#define LIS_REG_FIFO_SRC_ADDR                       0x2F
#define LIS_REG_INT1_CFG_ADDR                       0x30
#define LIS_REG_INT1_SRC_ADDR                       0x31
#define LIS_REG_INT1_THS_ADDR                       0x32
#define LIS_REG_INT1_DURATION_ADDR                       0x33
#define LIS_REG_INT2_CFG_ADDR                       0x34
#define LIS_REG_INT2_SRC_ADDR                       0x35
#define LIS_REG_INT2_THS_ADDR                       0x36
#define LIS_REG_INT2_DURATION_ADDR                       0x37
#define LIS_REG_CLICK_CFG_ADDR                       0x38
#define LIS_REG_CLICK_SRC_ADDR                       0x39
#define LIS_REG_CLICK_THS_ADDR                       0x3A
#define LIS_REG_TIME_LIMIT_ADDR                       0x3B
#define LIS_REG_TIME_LATENCY_ADDR                       0x3C
#define LIS_REG_TIME_WINDOW_ADDR                       0x3D
#define LIS_REG_ACT_THS_ADDR                       0x3E
#define LIS_REG_ACT_DUR_ADDR                       0x3F


/*******************************************************************************
  Flags                                                                              
*******************************************************************************/

/* CTRL1 Register Flags */
#define LIS_CTRL1_X_EN                       0x01
#define LIS_CTRL1_Y_EN                       0x02
#define LIS_CTRL1_Z_EN                       0x04
#define LIS_CTRL1_LOW_PWR                       0x08

/* CTRL2 Register Flags */
#define LIS_CTRL2_HP_IA1                       0x01
#define LIS_CTRL2_HP_IA2                       0x02
#define LIS_CTRL2_HPCLICK                       0x04
#define LIS_CTRL2_FDS                       0x08


/*******************************************************************************
  Field Values                                                                              
*******************************************************************************/

/* CTRL1 Register Fields */
  /* CTRL1 -> ODR */
  #define LIS_CTRL1_ODR_MASK        0xF0
  #define LIS_CTRL1_ODR_PWR_DWN      0x00
  #define LIS_CTRL1_ODR_1HZ      0x01
  #define LIS_CTRL1_ODR_10HZ      0x08
  #define LIS_CTRL1_ODR_25HZ      0x09
  #define LIS_CTRL1_ODR_50HZ      0x40
  #define LIS_CTRL1_ODR_100HZ      0x41
  #define LIS_CTRL1_ODR_200HZ      0x48
  #define LIS_CTRL1_ODR_400HZ      0x49
  #define LIS_CTRL1_ODR_1620HZ      0x07
  #define LIS_CTRL1_ODR_5376HZ      0x07

/*******************************************************************************
  Default Values                                                                              
*******************************************************************************/

#define LIS_WHO_AM_I_DEFAULT  0x33
#define LIS_TEMP_CFG_DEFAULT  0x10
#define LIS_CTRL2_DEFAULT  0x07

/*******************************************************************************
  Flag Set/Clear/Check                                                                             
*******************************************************************************/

/**
  *@brief sets flags on device
  *@param dev ptr to LIS2DH12 device
  *@param reg ptr to register definition
  *@param mask mask of flags to set
  */
#define lis_set_flag(dev, reg, mask) regdev_set_flags(&(dev)->mRegDev,(reg), (mask))

/**
  *@brief clears flags on device
  *@param dev ptr to LIS2DH12 device
  *@param reg ptr to register definition
  *@param mask mask of flags to set
  */
#define lis_clear_flag(dev, reg, mask) regdev_clear_flags(&(dev)->mRegDev,(reg), (mask))

/**
  *@brief checks flags on device
  *@param dev ptr to LIS2DH12 device
  *@param reg ptr to register definition
  *@param mask mask of flags to set
  *@return true if all flags in mask are set 
  *@return false if any flags in mask are not set
  */
#define lis_check_flag(dev, reg, mask) regdev_check_flags(&(dev)->mRegDev,(reg), (mask))

/*******************************************************************************
  Field Getters                                                                              
*******************************************************************************/

/**
 * @brief reads the ODR field from the device 
 * @param dev ptr to LIS2DH12 device
 * @return LIS_CTRL1_ODR_PWR_DWN Power-down mode
 * @return LIS_CTRL1_ODR_1HZ HR/ Normal / Low-power mode (1 Hz)
 * @return LIS_CTRL1_ODR_10HZ HR/ Normal / Low-power mode (10 Hz)
 * @return LIS_CTRL1_ODR_25HZ HR/ Normal / Low-power mode (25 Hz)
 * @return LIS_CTRL1_ODR_50HZ HR/ Normal / Low-power mode (50 Hz)
 * @return LIS_CTRL1_ODR_100HZ HR/ Normal / Low-power mode (100 Hz)
 * @return LIS_CTRL1_ODR_200HZ HR/ Normal / Low-power mode (200 Hz)
 * @return LIS_CTRL1_ODR_400HZ HR/ Normal / Low-power mode (400 Hz)
 * @return LIS_CTRL1_ODR_1620HZ Low-power mode (1.620 kHz)
 * @return LIS_CTRL1_ODR_5376HZ HR/ Normal (1.344 kHz) / Low-power mode (5.376 kHz)
 */
#define lis_get_ctrl1_odr(dev) regdev_read_field(dev->mRegDev, &(dev)->mCtrl1, LIS_CTRL1_ODR_MASK )


/*******************************************************************************
  Field Setters                                                                              
*******************************************************************************/

/**
 * @brief writes the ODR field from the device 
 * @param dev ptr to LIS2DH12 device
 * @option LIS_CTRL1_ODR_PWR_DWN Power-down mode
 * @option LIS_CTRL1_ODR_1HZ HR/ Normal / Low-power mode (1 Hz)
 * @option LIS_CTRL1_ODR_10HZ HR/ Normal / Low-power mode (10 Hz)
 * @option LIS_CTRL1_ODR_25HZ HR/ Normal / Low-power mode (25 Hz)
 * @option LIS_CTRL1_ODR_50HZ HR/ Normal / Low-power mode (50 Hz)
 * @option LIS_CTRL1_ODR_100HZ HR/ Normal / Low-power mode (100 Hz)
 * @option LIS_CTRL1_ODR_200HZ HR/ Normal / Low-power mode (200 Hz)
 * @option LIS_CTRL1_ODR_400HZ HR/ Normal / Low-power mode (400 Hz)
 * @option LIS_CTRL1_ODR_1620HZ Low-power mode (1.620 kHz)
 * @option LIS_CTRL1_ODR_5376HZ HR/ Normal (1.344 kHz) / Low-power mode (5.376 kHz)
 */
#define lis_set_ctrl1_odr(dev) regdev_write_field(dev->mRegDev, &(dev)->mCtrl1, LIS_CTRL1_ODR_MASK )
